VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0057.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0057
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0109.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0109
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0202.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0202
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0212.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0212
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0295.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0295
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0298.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0298
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0302.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0302
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0312.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0312
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0333_2.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0333_2
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0333.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0333
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0406_2.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0406_2
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0406.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0406
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0432.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0432
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0613.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0613
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0614.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0614
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0680.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0680
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0857.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0857
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0865.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0865
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0896.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/AD-0896
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/ADC-5021.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/ADC-5021
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/ADC-9006.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/ADC-9006
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/ADC-9007.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/ADC-9007
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/ADC-9012.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/ADC-9012
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/empty.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/empty
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/NTC.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/NTC
VarScan_Somatic_MIPS /home/yulywang/scratch/MIPS/FQ/somatic/ADC-6008.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/Posctrl.sort.bam /home/yulywang/scratch/MIPS/FQ/somatic/Posctrl
