#!/usr/bin/perl -w
sub usage (){
    die qq(
#===========================================================================
#        USAGE:relatives_annotate.pl  -h
#        DESCRIPTION: -h : Display this help
#        Author: Wang Yu
#        Will compare missing rate and the role for each sample.
#
#        Required file:
#        -g : [IBD File] Genome file generated by PLINK -genome
#
#        Optional file;
#        -m : [Missing File] Missing Rate for each sample, generated by PLINK
#
#        Mail: yulywang\@umich.edu
#        Created Time:  Fri 12 Oct 2018 12:11:05 PM EDT
#===========================================================================
)
}

use strict;
use warnings;
use Getopt::Std;
our ($opt_h,$opt_m, $opt_g);
getopts("hm:g:");
$opt_g || &usage();

my %miss; # record missing rate
my @F; # global variable;
my $relatives; 

if($opt_m){
	open MISS, "$opt_m";
	while(my $line = <MISS>){
		chomp $line;
		@F = split/\s+/,$line;
		$miss{$F[1]} = $F[6];
	}
}

open IBD, "$opt_g";
<IBD>; #skip header
if($opt_m){
	print "Delete\tID1\tID1_Role\tID2\tID2_Role\tZ1\tZ2\tPI_HAT\tRelative\tID1_MissRate\tID2_MissRate\n";
}else{
	print "ID1\tID1_Role\tID2\tID2_Role\tZ1\tZ2\tPI_HAT\tRelative\n";
}

open ROLE, "~/bin/FMD.sample.info";
my %role;
my %wgh = (  # weight of each role;
	'Control'	=> 5,
	'adult' => 1.6, 
	'family' => 3,
	'ped' => 1,
	'ped,ped_family' => 1.5,
	'ped_family'	=> 2
);

while(my $line = <ROLE>){
	@F = split/\s+/,$line;
	$role{$F[0]} = $F[1];
	$wgh{$F[0]} = $wgh{$F[1]};
}
close ROLE;

while(my $line = <IBD>){
	chomp $line;
	@F = split/\s+/,$line;
	next if ($F[10] < 0.19);
	$relatives = 'Relative';
	if($F[10] >= 0.8){
		$relatives = "Duplication";
	}elsif($F[10] >= 0.4 and $F[8] >= 0.8){
		$relatives = "Parent/Kids";
	}elsif($F[10] >= 0.4 and $F[8] < 0.8){
		$relatives = "Siblings";
	}

	if($opt_m){
		if($wgh{$F[1]} == $wgh{$F[3]}){
			if($role{$F[1]} eq "ped"){ # ped dup
				&compare;
				#print "Unknown\t$F[1]\t$role{$F[1]}\t$F[3]\t$role{$F[3]}\t$F[8]\t$F[9]\t$F[10]\t$relatives\t$miss{$F[1]}\t$miss{$F[3]}\n";
			}else{
				&compare;
			}
		}elsif($wgh{$F[1]} > $wgh{$F[3]}){
				&deletefirst();	
		}elsif($wgh{$F[1]} < $wgh{$F[3]}){
				&deletesecond();	
		}
	}# end if
	else{
			print "$F[1]\t$role{$F[1]}\t$F[3]\t$role{$F[3]}\t$F[8]\t$F[9]\t$F[10]\t$relatives\n";
		}
} # end while

sub compare(){ # when both role are same
		if($F[1] =~/CCF/ and $F[3] =~/UMAD/){
			print "$F[1]\t$F[1]\t$role{$F[1]}\t$F[3]\t$role{$F[3]}\t$F[8]\t$F[9]\t$F[10]\t$relatives\t$miss{$F[1]}\t$miss{$F[3]}\n";
		}elsif($F[1] =~/UMAD/ and $F[3] =~/CCF/){
			print "$F[3]\t$F[3]\t$role{$F[3]}\t$F[1]\t$role{$F[1]}\t$F[8]\t$F[9]\t$F[10]\t$relatives\t$miss{$F[3]}\t$miss{$F[1]}\n";
		}elsif($miss{$F[1]} > $miss{$F[3]}){ # print higher missing rate sample first
			print "$F[1]\t$F[1]\t$role{$F[1]}\t$F[3]\t$role{$F[3]}\t$F[8]\t$F[9]\t$F[10]\t$relatives\t$miss{$F[1]}\t$miss{$F[3]}\n";
		}elsif($miss{$F[1]} <= $miss{$F[3]}){
			print "$F[3]\t$F[3]\t$role{$F[3]}\t$F[1]\t$role{$F[1]}\t$F[8]\t$F[9]\t$F[10]\t$relatives\t$miss{$F[3]}\t$miss{$F[1]}\n";
		}
}
sub deletefirst(){
			print "$F[1]\t$F[1]\t$role{$F[1]}\t$F[3]\t$role{$F[3]}\t$F[8]\t$F[9]\t$F[10]\t$relatives\t$miss{$F[1]}\t$miss{$F[3]}\n";
}
sub deletesecond(){
			print "$F[3]\t$F[3]\t$role{$F[3]}\t$F[1]\t$role{$F[1]}\t$F[8]\t$F[9]\t$F[10]\t$relatives\t$miss{$F[3]}\t$miss{$F[1]}\n";
}
